#!/usr/bin/env node

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// Configuration
const STICKERS_INPUT_DIR = path.join(__dirname, '../_misc_files/other_stickers');
const STICKERS_OUTPUT_FILE = path.join(__dirname, '../src/data/otherStickers.ts');

// Ensure output directory exists
const outputDir = path.dirname(STICKERS_OUTPUT_FILE);
if (!fs.existsSync(outputDir)) {
  fs.mkdirSync(outputDir, { recursive: true });
}

// Find all SVG files
const files = fs.readdirSync(STICKERS_INPUT_DIR)
  .filter(file => file.endsWith('.svg'))
  .sort();

if (files.length === 0) {
  console.warn('⚠️  No sticker files found in', STICKERS_INPUT_DIR);
  
  // Create empty stickers file
  const emptyContent = `// Auto-generated other stickers data
// This file is generated by scripts/generateOtherStickers.js

export interface OtherSticker {
  name: string;
  file: string;
  data: string; // Base64 encoded SVG
}

export const OTHER_STICKERS: OtherSticker[] = [];
`;
  
  fs.writeFileSync(STICKERS_OUTPUT_FILE, emptyContent);
  console.log('✓ Created empty stickers file at', STICKERS_OUTPUT_FILE);
  process.exit(0);
}

// Convert files to Base64
const stickers = files.map(file => {
  const filePath = path.join(STICKERS_INPUT_DIR, file);
  const fileContent = fs.readFileSync(filePath);
  const base64 = fileContent.toString('base64');
  
  // Convert filename like "tree-evergreen.svg" to "treeevergreen"
  const name = file
    .replace(/\.svg$/, '')
    .replace(/-/g, '');
  
  return {
    name,
    file,
    data: base64
  };
});

// Generate TypeScript file
const tsContent = `// Auto-generated other stickers data
// This file is generated by scripts/generateOtherStickers.js
// Do not edit manually - regenerate using: npm run generate-stickers

export interface OtherSticker {
  name: string;
  file: string;
  data: string; // Base64 encoded SVG
}

export const OTHER_STICKERS: OtherSticker[] = ${JSON.stringify(stickers, null, 2)};
`;

fs.writeFileSync(STICKERS_OUTPUT_FILE, tsContent);
console.log(`✓ Generated stickers file with ${stickers.length} sticker(s)`);
console.log(`  Location: ${STICKERS_OUTPUT_FILE}`);
stickers.forEach(sticker => {
  console.log(`  - ${sticker.name} (${sticker.file})`);
});
