#!/usr/bin/env node

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// Configuration
const SIGNS_INPUT_DIR = path.join(__dirname, '../_misc_files/signs');
const SIGNS_OUTPUT_FILE = path.join(__dirname, '../src/data/signs.ts');

// Ensure output directory exists
const outputDir = path.dirname(SIGNS_OUTPUT_FILE);
if (!fs.existsSync(outputDir)) {
  fs.mkdirSync(outputDir, { recursive: true });
}

// Find all SVG files with "sign_" prefix
const files = fs.readdirSync(SIGNS_INPUT_DIR)
  .filter(file => file.startsWith('sign_') && file.endsWith('.svg'))
  .sort();

if (files.length === 0) {
  console.warn('⚠️  No sign files found in', SIGNS_INPUT_DIR);
  console.warn('Expected files like: sign_dpvj.svg, sign_hlavna.svg, etc.');
  
  // Create empty signs file
  const emptyContent = `// Auto-generated signs data
// This file is generated by scripts/generateSigns.js

export interface Sign {
  name: string;
  file: string;
  data: string; // Base64 encoded SVG
}

export const SIGNS: Sign[] = [];
`;
  
  fs.writeFileSync(SIGNS_OUTPUT_FILE, emptyContent);
  console.log('✓ Created empty signs file at', SIGNS_OUTPUT_FILE);
  process.exit(0);
}

// Convert files to Base64
const signs = files.map(file => {
  const filePath = path.join(SIGNS_INPUT_DIR, file);
  const fileContent = fs.readFileSync(filePath);
  const base64 = fileContent.toString('base64');
  
  // Convert filename like "sign_dpvj.svg" to "dpvj"
  const name = file
    .replace(/^sign_/, '')
    .replace(/\.svg$/, '')
    .toLowerCase();
  
  return {
    name,
    file,
    data: base64
  };
});

// Generate TypeScript file
const tsContent = `// Auto-generated signs data
// This file is generated by scripts/generateSigns.js
// Do not edit manually - regenerate using: npm run generate-signs

export interface Sign {
  name: string;
  file: string;
  data: string; // Base64 encoded SVG
}

export const SIGNS: Sign[] = ${JSON.stringify(signs, null, 2)};
`;

fs.writeFileSync(SIGNS_OUTPUT_FILE, tsContent);
console.log(`✓ Generated signs file with ${signs.length} sign(s)`);
console.log(`  Location: ${SIGNS_OUTPUT_FILE}`);
signs.forEach(sign => {
  console.log(`  - ${sign.name} (${sign.file})`);
});
